import "./globals.css";
// import Navbar from "/components/Navbar";
import Navbar from "../components/Navbar";
import Image from "next/image";
import bgImage from "../../public/home-page-bg.png";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white">
        <div className="w-full absolute z-[-10]">
          <Image src={bgImage} className="" />
        </div>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
