import "./globals.css";
// import Navbar from "/components/Navbar";
import Navbar from "../components/Navbar";
import Image from "next/image";
import bgImage from "../../public/home-page-bg.png";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white relative">
        <div className="w-full">
          <Image src={bgImage} className="absolute z-[-10]" />
        </div>
        <Navbar />
        <div className="">{children}</div>

        {/* <div className="absolute bottom-0 h-20 bg-white w-full"></div> */}
      </body>
    </html>
  );
}
