import "../globals.css";
import Image from "next/image";
import Navbar from "../../components/Navbar";
import bgImage from "../../../public/home-page-bg.png";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="text-white relative">
        <div className="w-full">
          <Image alt="bgImage" src={bgImage} className="absolute z-[-10]" />
        </div>
        <Navbar />
        <div className="mt-11 px-[110px]">{children}</div>

        {/* <div className="absolute bottom-0 h-20 bg-white w-full"></div> */}
      </body>
    </html>
  );
}
